# Generated by Django 5.2.15 on 2026-08-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='cover',
            field=models.ImageField(default='default_cover.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='track',
            name='lyrics',
            field=models.TextField(blank=True),
        ),
    ]
