# Generated by Django 5.2.15 on 2026-08-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_track_cover_alter_track_lyrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='cover',
            field=models.ImageField(default='default-cover.png', upload_to=''),
        ),
    ]
