# Generated by Django 5.2.15 on 2026-08-01 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_alter_track_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='photo',
            field=models.ImageField(default='default-artist.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='track',
            name='artist',
            field=models.ManyToManyField(to='Core.artist'),
        ),
    ]
