# Generated by Django 5.2.15 on 2026-08-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_artist_photo_track_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='cover',
            field=models.ImageField(default='default-cover.png', upload_to='covers/'),
        ),
    ]
