# Generated by Django 5.2.15 on 2026-08-02 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_alter_track_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='featured_artist',
            field=models.ManyToManyField(blank=1, null=1, related_name='featured_tracks', to='Core.artist'),
            preserve_default=1,
        ),
        migrations.RemoveField(
            model_name='track',
            name='artist',
        ),
        migrations.AddField(
            model_name='track',
            name='artist',
            field=models.ForeignKey(blank=1, null=1, on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='Core.artist'),
            preserve_default=1,
        ),
    ]
