# Generated by Django 5.2.15 on 2026-08-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_track_featured_artist_remove_track_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='description',
            field=models.TextField(blank=1, null=1),
            preserve_default=1,
        ),
        migrations.AddField(
            model_name='track',
            name='release_date',
            field=models.DateTimeField(blank=1, null=1),
            preserve_default=1,
        ),
    ]
