# Generated by Django 5.2.15 on 2026-08-07 16:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_track_description_track_release_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=1)),
            ],
        ),
        migrations.AlterField(
            model_name='artist',
            name='description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.ForeignKey(blank=1, null=1, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='Core.artist'),
        ),
        migrations.AlterField(
            model_name='track',
            name='genres',
            field=models.ManyToManyField(related_name='rel_track', to='Core.genre'),
        ),
        migrations.AlterField(
            model_name='track',
            name='release_date',
            field=models.DateTimeField(blank=1, default=django.utils.timezone.now, null=1),
        ),
        migrations.CreateModel(
            name='Album_track_relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.album')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.track')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='tracks',
            field=models.ManyToManyField(through='Core.Album_track_relation', to='Core.track'),
        ),
    ]
