# Generated by Django 5.2.15 on 2026-08-09 21:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_album_alter_artist_description_alter_track_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='genres',
            field=models.ManyToManyField(related_name='rel_album', to='Core.genre'),
        ),
        migrations.AddField(
            model_name='album',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='album',
            name='release_date',
            field=models.DateTimeField(blank=1, default=django.utils.timezone.now, null=1),
            preserve_default=1,
        ),
        migrations.AddField(
            model_name='album',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='genres',
            field=models.ManyToManyField(related_name='rel_artist', to='Core.genre'),
        ),
        migrations.AlterField(
            model_name='album_track_relation',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracksz', to='Core.album'),
        ),
        migrations.AlterField(
            model_name='album_track_relation',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albumm', to='Core.track'),
        ),
        migrations.AlterField(
            model_name='track',
            name='description',
            field=models.TextField(blank=1, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='track',
            name='featured_artist',
            field=models.ManyToManyField(blank=1, related_name='featured_tracks', to='Core.artist'),
        ),
    ]
