# Generated by Django 5.2.15 on 2026-08-15 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_album_date_added_album_genres_album_likes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='bugreport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=1, max_length=100)),
                ('description', models.TextField()),
                ('email', models.EmailField(blank=1, max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='album_track_relation',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackr', to='Core.album'),
        ),
        migrations.AlterField(
            model_name='album_track_relation',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albumr', to='Core.track'),
        ),
    ]
