# Generated by Django 5.2.15 on 2026-08-15 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0010_bugreport_alter_album_track_relation_album_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bugreport',
            new_name='Feedback',
        ),
    ]
