# Generated by Django 5.2.15 on 2026-08-25 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0012_playlist_playlist_track_relation_playlist_tracks'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='audio_file',
            field=models.FileField(blank=1, null=1, upload_to='tracks/'),
            preserve_default=1,
        ),
        migrations.AlterField(
            model_name='album_track_relation',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albumr', to='Core.album'),
        ),
    ]
