# Generated by Django 5.2.15 on 2026-08-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0013_track_audio_file_alter_album_track_relation_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
