# Generated by Django 5.2.15 on 2026-10-05 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0014_playlist_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='description',
            field=models.TextField(blank=1),
        ),
    ]
