# Generated by Django 5.2.15 on 2026-10-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0015_alter_artist_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
